### ISSUE TITLE
HttpEndpoint in gateway implementation must be released

### ISSUE THREAD

**Issue by Flazher** [sczyh30/vertx-blueprint-microservice#25]
Hello,

According to Vert'x documentation, every used service reference (including **HttpEndpointReference**) must be eventually released.
http://vertx.io/docs/vertx-service-discovery/java/#_http_endpoints
However, you missed that step in your gateway implementation. In case of using **HttpEndpointReference**, it leads us to a bunch of established socket connections and, eventually, disability to create new connections whatsoever.

**Comment by mechanik0s** [comment]
Same problem

**Comment by sczyh30** [comment]
Thanks for reporting this! I'll fix this and find a better approach to reuse the connections.

**Comment by mechanik0s** [comment]
Maybe we should not retrieve service reference from service discovery during dispatching
```
doDispatch(context, newPath, discovery.getReference(client.get()).get(), future)
```
That leads us to create new Service Reference (and HttpClient inside this reference) every time. On the contrary, we must use the already created HttpClient, which can be obtained from the cache in method [AbstractServiceReference.get()](http://vertx.io/docs/apidocs/io/vertx/servicediscovery/types/AbstractServiceReference.html#get--)

**Comment by sczyh30** [comment]
Yes, we are refactoring the architecture of API Gateway at present. We'll make a better way to reuse the resources (maybe cached client pools) to improve performance.

**Comment by sczyh30** [comment]
There will be a huge change of the microservice architecture in next version. And any suggestions about the architecture design is welcome :-)
