### ISSUE TITLE
Add ELK logging integration

### ISSUE THREAD

**Issue by sczyh30** [sczyh30/vertx-blueprint-microservice#3]
Add ELK logging integration in the microservice blueprint.

**Comment by crazyfrozenpenguin** [comment]
What do you want to use here?

Logstash-GELF is a great option here. What are thinking in terms of logging libs? slf4j + log4j2 bridge are good options. Thoughts?

**Comment by sczyh30** [comment]
Yeah, SLF4J + Log4j2 can be a good choice as logging libs. As for ELK integration, there is a good example we can reference: [Centralized logging for Vert.x applications using the ELK stack](http://vertx.io/blog/centralized-logging-for-vert-x-applications-using-the-elk-stack/). But I'm not familiar with ELK stack... What do you think of the example compared with Logstash-GELF?

**Comment by cescoffier** [comment]
The appender approach is less and less used. It lacks of flexibility (ask settings for instance), and can be dangerous to use (blocking calls to a distributed system).

If you want to use ELK, you should avoid appenders and use FileBeat to read, parse and send your logs.

**Comment by crazyfrozenpenguin** [comment]
I've added an implementation using Vert.x SLF4J Log4J. Logstash GELF format appender used. This should suffice but I'll have a look into _FileBeat_.

**Comment by crazyfrozenpenguin** [comment]
Just converted log4j appenders to async appenders which should guarantee non-blocking solution.

In addition, I had a quick look into Elasticsearch FileBeat and apparently it requires a log file to "attach to". In other words, we will have to log to local file and then use FileBeat to send the logs to Logstash. There's actually an example in Vert.x documentation [here](http://vertx.io/blog/centralized-logging-for-vert-x-applications-using-the-elk-stack/#filebeat-configuration)

This might be a good alternative if external volumes for the log files are mounted to the docker containers.

Thoughts?
